name: Build and push to Docker Hub
on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v2
      
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
          repository: calpismate/radicast
          context: .
          push: true
          tag_with_ref: true
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
