name: Build and push
on: 
  push:
    branches: 
      - master
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v2
      
      - name: Get Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: calpismate/radicast

      - name: Build Docker image
        if: github.ref != 'refs/heads/master' && contains(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          push: false

      - name: Build and push Docker image as latest
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          tags: latest
          push: true

      - name: Build and push Docker image with version number
        if: contains(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          push: true
