name: Build and push
on: 
  push:
    branches: 
      - master
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v2
      
      - name: Get Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: calpismate/radicast

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          push: false
          load: true
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      - name: Export Docker image from local
        run: docker save ${{ steps.meta.outputs.tags }} | gzip -c > /tmp/radicast-image.tar.gz
  
      - name: Upload Docker image as an articact
        if: github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: radicast-image
          path: /tmp/radicast-image.tar.gz

  push:
    needs: build
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    if: github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/')
    steps:
      - name: Download Docker image from the artifact
        uses: actions/download-artifact@v2
        with:
          name: radicast-image
          path: /tmp
      
      - name: Get Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: calpismate/radicast

      - name: Load Docker image
        run: |
          cat /tmp/radicast-image.tar.gz | gzip -d | docker load
          docker image ls ${{ steps.meta.outputs.tags }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
